.PHONY: clean All

All:
	@echo "----------Building project:[ box_lock - Debug ]----------"
	@cd "box_lock" && "$(MAKE)" -f  "box_lock.mk"
clean:
	@echo "----------Cleaning project:[ box_lock - Debug ]----------"
	@cd "box_lock" && "$(MAKE)" -f  "box_lock.mk" clean
