#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
# 
#############################################################################

TARGET := db103

# specify where the bmptk files can be found, using an absolute path
BMPTK := F:/____bmptk/bmptk/

# defer to the bmptk Makefile.inc to do the work
include $(BMPTK)Makefile.inc
