#############################################################################
# 
# Makefile that just passes the work to its subdirectories.
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
# 
#############################################################################

# blink-a-led example
SUBDIRS += blink

# let the higher level Makefile.subdirs do the work
include ../Makefile.subdirs

