#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
# 
#############################################################################

STACK_SIZE        := AUTOMATIC
ANNOTATE          := YES
PROJECT_CPP_FLAGS += -ftemplate-depth=100000

# set BMPTK to the next higher directory
BMPTK := $(BMPTK)../

# Defer to the next higher Makefile.inc to do the work
include $(BMPTK)Makefile.inc