#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
#
#############################################################################

# Specify target chip or board or system
TARGET     := stm32f411nucleo

# Specify the location of the bmptk library
BMPTK      := ../../../..

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
