#############################################################################
# 
# Makefile that just passes the work to its subdirectories.
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at 
# http://www.boost.org/LICENSE_1_0.txt)
# 
#############################################################################

# examples for the Arduino Uno (atMega318p)
SUBDIRS += arduino_uno

# examples for the Arduino Due (ATSAM3X8E)
SUBDIRS += arduino_due

# examples for TI MSP430 boards
SUBDIRS += msp_exp430fr4133
SUBDIRS += msp_exp430g2

# examples for the LPC800-mini-kit (lpc810m021f)
SUBDIRS += lpc800_mini_kit

# examples for the LPC800-max (lpc812m101jdh16)
SUBDIRS += lpc800_max

# examples for the HU ARM v4 (lpc2148fbd64)
SUBDIRS += hu_arm_v4

# examples for the tiny_11c14 (lpc11c14fbd48)
SUBDIRS += tiny_11c14

# examples for the VOTI DB013 (LPC1114)
SUBDIRS += db103

# examples for the VOI DB014 (LPC1114 + 7-segment display)
SUBDIRS += db104

# examples for the VOTI DB105 (LPC810)
SUBDIRS += db105

# examples for the Freescale Freedom KL25Z
SUBDIRS += frdm_kl25z

# examples for the stm boards
SUBDIRS += stm32f0discovery
SUBDIRS += stm32f411nucleo
SUBDIRS += stm32l1discovery

# examples for the Infineon boards
SUBDIRS += xmc_2go_1100

# examples for running native
SUBDIRS += native

# let the higher level Makefile.subdirs do the work
include ../Makefile.subdirs

