#############################################################################
# 
# Makefile that just passes the work to its subdirectories.
#
# (c) Wouter van Ooijen (www.voti.nl) 2012 ... 2015
#
# This file is in the public domain.
# 
#############################################################################

SUBDIRS += boards
SUBDIRS += courses
SUBDIRS += talks

# The Makefile.subdirs does the work
include ../Makefile.subdirs

