#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
#
#############################################################################

# Specify target chip or board or system
TARGET     := esp-01

# Specify the location of the bmptk library
BMPTK      := ../../../..

# RESULTS    := main.lst

SERIAL_BAUDRATE = 454800

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
